const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('assert'),path=require('path'),fs=require('fs'),os=require('os');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});const checks=[],errors=[];try{const page=await browser.newPage({viewport:{width:1600,height:1100}});page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto(require('url').pathToFileURL(path.join(__dirname,'index.html')).href);await page.waitForTimeout(1600);
assert(await page.locator('.h-dashboard').isVisible());assert.equal(await page.locator('[data-view=profiles] .rail-label').innerText(),'Profile 360');checks.push('Dashboard and navigation');
await page.locator('#h-owner').selectOption('All');await page.waitForTimeout(250);await page.screenshot({path:path.join(os.tmpdir(),'hub06-dashboard.png')});
// All original screens and the new Profile 360 screen still render.
const views=await page.locator('.view').evaluateAll(es=>es.map(e=>e.id.replace('view-','')));for(const v of views){await page.evaluate(v=>setView(v),v);await page.waitForTimeout(70)}checks.push('All '+views.length+' views');
await page.evaluate(()=>hubOpen('omnichannel'));await page.locator('[data-h-thread]').first().click();const key=await page.locator('.h-thread.active').getAttribute('data-h-thread');await page.locator('#h-message-draft').fill('Bản nháp riêng cho kênh');await page.locator('[data-h-thread]').nth(1).click();assert.notEqual(await page.locator('#h-message-draft').inputValue(),'Bản nháp riêng cho kênh');await page.locator('[data-h-thread]').first().click();assert.equal(await page.locator('#h-message-draft').inputValue(),'Bản nháp riêng cho kênh');const before=await page.evaluate(()=>state.messages.length);await page.locator('#h-chat-send').click();await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>state.messages.length),before+1);const sent=await page.evaluate(()=>state.messages.at(-1));assert.equal(sent.channel,JSON.parse(key)[1]);assert.equal(sent.account,JSON.parse(key)[2]);assert.equal(sent.body,'Bản nháp riêng cho kênh');checks.push('Channel/account separation, drafts and local reply');
for(const c of ['Facebook Page','Zalo OA','Zalo Personal']){await page.locator(`[data-chat-channel="${c}"]`).click();assert(await page.locator('[data-h-thread]').evaluateAll((bs,c)=>bs.every(b=>JSON.parse(b.dataset.hThread)[1]===c),c))}await page.screenshot({path:path.join(os.tmpdir(),'hub06-chat.png')});
await page.evaluate(()=>hubOpen('profiles'));await page.locator('[data-profile-open]').first().click();await page.waitForTimeout(100);assert(await page.locator('#drawer-family').isVisible());await page.locator('.profile-tabs [data-profile-layer=student]').click();assert(await page.locator('#drawer-student').isVisible());await page.locator('.profile-tabs [data-profile-layer=deal]').click();assert(await page.locator('#drawer-deal').isVisible());await page.screenshot({path:path.join(os.tmpdir(),'hub06-profile.png')});await page.keyboard.press('Escape');checks.push('Profile 360 three layers');
await page.evaluate(()=>hubOpen('pipeline'));await page.locator('[data-pipe-stage="Marketing Qualified Leads"]').click();await page.locator('[data-pipe-sub="Hot"]').click();assert(await page.locator('.h-pipeline-record').evaluateAll(es=>es.every(e=>/Hot|Nóng/.test(e.innerText))));checks.push('Stages and sub-stage filter');await page.screenshot({path:path.join(os.tmpdir(),'hub06-pipeline.png')});
// Use a clean source opportunity; no production/browser-profile data is touched.
const fixture=await page.evaluate(()=>{const o=state.opportunities.find(o=>o.stage==='Leads'&&o.bu==='CIS'&&!findOpenDealConflict(o.studentId,o.bu,o.id)),h=householdObj(state,o.householdId),s=studentObj(state,o.studentId);state.activeOpp=o.id;return {id:o.id,parent:h.primaryName,phone:h.phone,email:h.email,student:s.name,grade:s.grade}});
await page.evaluate(()=>{openStageModal();pendingStage='Marketing Qualified Leads';renderStageForm();document.querySelector('.ux-stage-choice').open=false});await page.waitForTimeout(100);
await page.evaluate(()=>{document.querySelectorAll('[id^=qcheck]').forEach(c=>c.checked=false)});assert.equal(await page.evaluate(()=>validateStage().ok),false);await page.evaluate(()=>{for(let i=0;i<6;i++){const c=document.querySelector('#qcheck'+i);c.checked=true;c.dispatchEvent(new Event('change',{bubbles:true}))}for(const id of ['sgGrade','sgIntake','sgProgram','sgDistrict','sgConcern','sgNext']){const el=document.getElementById(id);if(!el.value)el.value='Thông tin đã xác minh'}});assert.equal(await page.evaluate(()=>validateStage().derived),'Hot');
const ratings=await page.evaluate(()=>[2,3,4,5,6].map(n=>deriveMql(Array.from({length:6},(_,i)=>i<n))));assert.deepEqual(ratings,['Cold','Warm','Warm','Hot','Hot']);await page.screenshot({path:path.join(os.tmpdir(),'hub06-checklist.png')});
while(await page.locator('#stageModalOverlay .ux-form-next:visible').count())await page.locator('#stageModalOverlay .ux-form-next').click();await page.locator('#confirmStageBtn').click();await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>oppObj(state,state.activeOpp).substage),'Hot');assert(await page.locator('.qa-undo').isVisible());await page.locator('.qa-undo').click();await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>oppObj(state,state.activeOpp).stage),'Leads');checks.push('MQL Q1/Q2 gate, Cold/Warm/Hot derivation, apply and undo');
await page.evaluate(()=>{openStageModal();pendingStage='In Consideration';renderStageForm();document.querySelector('.ux-stage-choice').open=false});await page.waitForTimeout(100);const levels=await page.evaluate(()=>[derivePotential([true,true,true,false,false,false],'Under 30 days'),derivePotential([true,true,true,true,false,false],'30–60 days'),derivePotential([true,true,true,true,true,false],'Under 30 days'),derivePotential([true,true,true,true,true,true],'Unclear / 60+ days')]);assert.deepEqual(levels,['Low','Medium','High','Low']);await page.evaluate(()=>{document.querySelectorAll('[id^=pcheck]').forEach(c=>c.checked=true);document.querySelector('#sgTimeline').value='Under 30 days';document.querySelector('#sgFeeOffer').value='';document.querySelector('#sgPaymentDate').value='';document.querySelector('#sgNext').value='Gọi lại';document.querySelector('#sgBlocker').value='Không';});assert.equal(await page.evaluate(()=>validateStage().ok),false);await page.evaluate(()=>{document.querySelector('#sgPaymentDate').value='2026-10-01';document.querySelector('#sgFeeOffer').value='340000000'});assert.equal(await page.evaluate(()=>validateStage().derived),'High');await page.keyboard.press('Escape');await page.keyboard.press('Escape');checks.push('Potential Low/Medium/High and High payment/forecast gate');
async function createDraft(student,bu){await page.evaluate(()=>openLeadWizard());await page.waitForTimeout(150);await page.locator('#nlParent').fill(fixture.parent);await page.locator('#nlPhone').fill(fixture.phone.replace(/\D/g,''));await page.locator('#leadNextBtn').click();await page.waitForTimeout(200);await page.locator('#nlStudent').fill(student);await page.locator('#nlGrade').fill(fixture.grade);await page.locator('#leadNextBtn').click();await page.locator('#nlBu').selectOption(bu);await page.locator('#leadNextBtn').click();}
const count=await page.evaluate(()=>state.opportunities.length);await createDraft(fixture.student,'SSV');await page.locator('#leadNextBtn').click();assert.equal(await page.evaluate(()=>state.opportunities.length),count);assert(await page.locator('#leadModalOverlay').evaluate(e=>e.classList.contains('open')));await page.keyboard.press('Escape');await createDraft(fixture.student,'CIS');await page.locator('#leadNextBtn').click();assert.equal(await page.evaluate(()=>state.opportunities.length),count);await page.keyboard.press('Escape');checks.push('Cross CIS/SSV and same-BU duplicate creation blocked');
await createDraft('Học sinh QA anh chị em','SSV');await page.locator('#leadNextBtn').click();await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>state.opportunities.length),count+1);assert(await page.evaluate(id=>oppObj(state,state.activeOpp).householdId===oppObj(state,id).householdId,fixture.id));await page.keyboard.press('Escape');checks.push('Sibling linked without merging students');
assert.equal(await page.evaluate(()=>hubIdentify({phone:'',email:'nonexistent@example.invalid',student:'Someone'}).h),undefined);checks.push('Blank phone does not match unrelated household');
// Reopening an otherwise closed CIS/SSV record cannot bypass conflict checks.
assert(await page.evaluate(id=>{const existing=oppObj(state,id),clone={...existing,id:'QA-CLOSED-CONFLICT',bu:'SSV',stage:'No Sign-up',status:'Closed'};state.opportunities.push(clone);state.activeOpp=clone.id;openStageModal();pendingStage='Marketing Qualified Leads';renderStageForm();const blocked=!validateStage().ok;state.opportunities=state.opportunities.filter(o=>o.id!==clone.id);document.querySelector('#stageModalOverlay').classList.remove('open');return blocked},fixture.id));checks.push('Reopening gate blocks K12 conflict');
await page.reload();await page.waitForTimeout(1200);assert.equal(await page.evaluate(()=>state.opportunities.length),count+1);checks.push('Persistence');
for(const width of [1600,1280,1024,768,390]){await page.setViewportSize({width,height:1000});for(const v of ['dashboard','profiles','omnichannel','pipeline']){await page.evaluate(v=>hubOpen(v),v);await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width,`${v} at ${width}`)}}checks.push('Four principal workspaces at five responsive widths');
await page.evaluate(()=>hubOpen('dashboard'));await page.screenshot({path:path.join(os.tmpdir(),'hub06-mobile.png'),fullPage:true});assert.deepEqual(errors,[]);const result={date:'2026-09-24',browser:'Chrome, isolated Playwright context',checks,pageErrors:errors,views};fs.writeFileSync(path.join(__dirname,'verification.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
